# Generated by Django 4.2.27 on 2026-01-31 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("C_start", models.FloatField()),
                ("T", models.IntegerField()),
                ("P", models.FloatField()),
                ("Q", models.IntegerField()),
                ("g", models.FloatField(blank=True, null=True)),
                ("E_var", models.FloatField()),
                ("E_fix", models.FloatField()),
                ("C_startup", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
