# Generated by Django 4.2.27 on 2026-01-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biz", "0002_businessmodel_marketing_budget_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BusinessModel",
        ),
    ]
